global:
    scrape_interval:     15s
    evaluation_interval: 15s
  
# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
    - "alert.rules"
scrape_configs:
    - job_name: cadvisor
      scrape_interval: 15s
      static_configs:
#      - targets:
#        - cadvisor:8080
      - targets: ['10.10.14.116:8184','10.10.14.124:8184']